apiVersion: v2
name: federated-pipeline
description: A Helm chart for Federated Learning Pipeline
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - federated-learning
  - machine-learning
  - distributed-systems
  - sdr
  - signal-processing
home: https://github.com/company/federated-pipeline
sources:
  - https://github.com/company/federated-pipeline
maintainers:
  - name: DevOps Team
    email: devops@company.com
dependencies:
  - name: postgresql
    version: "12.1.9"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.3.7"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: prometheus
    version: "15.18.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.50.7"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled
annotations:
  category: MachineLearning