# Production environment configuration
environment: production
debug: false

database:
  host: postgres-prod
  database: federated_pipeline_prod

network:
  port: 8000
  max_connections: 1000

federated_learning:
  min_clients: 10
  max_clients: 1000
  rounds: 50

privacy:
  enable_differential_privacy: true
  epsilon: 0.5

monitoring:
  log_level: "WARNING"
  enable_tracing: false